/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.anderson.ashley.gg;

import io.anderson.ashley.gg.validation.ValidationConfig;
import io.anderson.ashley.gg.web.WebConfig;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.properties.EnableConfigurationProperties;

@SpringBootApplication
@EnableConfigurationProperties({ ValidationConfig.class, WebConfig.class })
public class Main
{
	public static void main(final String[] args)
	{
		SpringApplication.run(Main.class, args);
	}
}
