spring:
  application:
    name: gg-task-web
  datasource:
    url:
      jdbc:h2:mem:requests
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

web:
  entry-record-delimiter: |
  ip-validation-enabled: true
  data-validation-enabled: true

validation:
  request-url: http://ip-api.com/json/
  request-fields:
    - status
    - message
    - countryCode
    - isp
  blocked-countries:
    - CN # China
    - ES # Spain
    - US # USA
  blocked-providers:
    - Amazon    # Amazon.com, Inc.      # AWS
    - Google    # Google LLC            # GCP
    - Microsoft # Microsoft Corporation # Azure
