/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.anderson.ashley.gg.web;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.properties.EnableConfigurationProperties;

@SpringBootApplication
@EnableConfigurationProperties(WebConfig.class)
public class Main
{
	public static void main(final String[] args)
	{
		SpringApplication.run(Main.class, args);
	}
}
