/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.anderson.ashley.gg.log;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Main
{
	public static void main(final String[] args)
	{
		SpringApplication.run(Main.class, args);
	}
}
